# Generated by Django 5.0.6 on 2024-05-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('emirate', models.CharField(choices=[('abudhabi', 'Abu Dhabi'), ('dubai', 'Dubai'), ('sharja', 'Sharjah'), ('ajman', 'Ajman'), ('ummalquwain', 'Umm Al Quwain'), ('rasalkhaimah', 'as Al Khaimah'), ('fujairah', 'Fujairah')], default='dubai')),
            ],
        ),
    ]
