# Generated by Django 5.0.6 on 2024-05-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='passport_number',
            field=models.CharField(max_length=25),
        ),
    ]
