# Generated by Django 5.0.6 on 2024-05-12 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_city_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emirate',
            field=models.CharField(choices=[('abudhabi', 'Abu Dhabi'), ('dubai', 'Dubai'), ('sharjah', 'Sharjah'), ('ajman', 'Ajman'), ('ummalquwain', 'Umm Al Quwain'), ('rasalkhaimah', 'Ras Al Khaimah'), ('fujairah', 'Fujairah')], default='dubai'),
        ),
    ]
